version: '3'

services:
  db:
    image: postgis/postgis
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
#     volumes:
#       - pg_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  
    ports:
      - 1025:1025 
      - 8025:8025 

# volumes:
#   pg_data: